package fr.ribesg.minecraft.purpur

import java.util.Properties
import kotlin.text.Regex

/**
 * Internal properties from purpur.properties, with values generated by Maven.
 *
 * @author Ribesg
 */
public object Props {

    /**
     * Maven Project Name
     */
    public val name: String

    /**
     * Maven Version
     */
    public val version: String

    /**
     * Regex for raw server log line parsing
     */
    public val regexLine: Regex

    /**
     * Regex triggering
     * [fr.ribesg.minecraft.purpur.event.CreateServerPropertiesEvent].
     */
    public val regexCreateServerProperties: Regex

    /**
     * Regex triggering
     * [fr.ribesg.minecraft.purpur.event.EulaRequiresAgreementEvent].
     */
    public val regexEulaRequiresAgreement: Regex

    /**
     * Regex triggering
     * [fr.ribesg.minecraft.purpur.event.ServerReadyEvent].
     */
    public val regexServerReady: Regex

    /**
     * Properties
     */
    private val props: Properties

    /**
     * Load properties from resource file
     */
    init {
        props = Properties()
        props.load(ClassLoader.getSystemResourceAsStream("purpur.properties"))

        name = props["name"] as String
        version = props["version"] as String

        regexLine = (props["regex_Line"] as String).toRegex()
        regexCreateServerProperties = (props["regex_CreateServerProperties"] as String).toRegex()
        regexEulaRequiresAgreement = (props["regex_EulaRequiresAgreement"] as String).toRegex()
        regexServerReady = (props["regex_ServerReady"] as String).toRegex()
    }
}
