package fr.ribesg.minecraft.purpur

import java.util.Properties

/**
 * Internal properties from purpur.properties, with values generated by Maven.
 *
 * @author Ribesg
 */
public object Props {

    /**
     * Maven Project Name
     */
    public val name: String

    /**
     * Maven Version
     */
    public val version: String

    /**
     * Properties
     */
    private val props: Properties

    /**
     * Load properties from resource file
     */
    init {
        props = Properties()
        props.load(ClassLoader.getSystemResourceAsStream("purpur.properties"))

        name = props["name"] as String
        version = props["version"] as String
    }
}
